name: pingpongbuddy
description: AI-powered table tennis swing analyzer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  drift: ^2.32.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  freezed_annotation: ^3.0.0
  get_it: ^9.2.1
  go_router: ^17.2.0
  json_annotation: ^4.11.0
  sqlite3_flutter_libs: ^0.5.32

dev_dependencies:
  bloc_lint: ^0.4.0
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.23
  build_runner: ^2.13.1
  drift_dev: ^2.32.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
